# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cagedbird/Projects/MSPM0_APPS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cagedbird/Projects/MSPM0_APPS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cagedbird/Projects/MSPM0_APPS/CMakeFiles /home/cagedbird/Projects/MSPM0_APPS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cagedbird/Projects/MSPM0_APPS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MSPM0G3507App.elf

# Build rule for target.
MSPM0G3507App.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MSPM0G3507App.elf
.PHONY : MSPM0G3507App.elf

# fast build rule for target.
MSPM0G3507App.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MSPM0G3507App.elf.dir/build.make CMakeFiles/MSPM0G3507App.elf.dir/build
.PHONY : MSPM0G3507App.elf/fast

generated/G3507/ti_msp_dl_config.o: generated/G3507/ti_msp_dl_config.c.o
.PHONY : generated/G3507/ti_msp_dl_config.o

# target to build an object file
generated/G3507/ti_msp_dl_config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MSPM0G3507App.elf.dir/build.make CMakeFiles/MSPM0G3507App.elf.dir/generated/G3507/ti_msp_dl_config.c.o
.PHONY : generated/G3507/ti_msp_dl_config.c.o

generated/G3507/ti_msp_dl_config.i: generated/G3507/ti_msp_dl_config.c.i
.PHONY : generated/G3507/ti_msp_dl_config.i

# target to preprocess a source file
generated/G3507/ti_msp_dl_config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MSPM0G3507App.elf.dir/build.make CMakeFiles/MSPM0G3507App.elf.dir/generated/G3507/ti_msp_dl_config.c.i
.PHONY : generated/G3507/ti_msp_dl_config.c.i

generated/G3507/ti_msp_dl_config.s: generated/G3507/ti_msp_dl_config.c.s
.PHONY : generated/G3507/ti_msp_dl_config.s

# target to generate assembly for a file
generated/G3507/ti_msp_dl_config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MSPM0G3507App.elf.dir/build.make CMakeFiles/MSPM0G3507App.elf.dir/generated/G3507/ti_msp_dl_config.c.s
.PHONY : generated/G3507/ti_msp_dl_config.c.s

src/common/gpio_toggle_output.o: src/common/gpio_toggle_output.c.o
.PHONY : src/common/gpio_toggle_output.o

# target to build an object file
src/common/gpio_toggle_output.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MSPM0G3507App.elf.dir/build.make CMakeFiles/MSPM0G3507App.elf.dir/src/common/gpio_toggle_output.c.o
.PHONY : src/common/gpio_toggle_output.c.o

src/common/gpio_toggle_output.i: src/common/gpio_toggle_output.c.i
.PHONY : src/common/gpio_toggle_output.i

# target to preprocess a source file
src/common/gpio_toggle_output.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MSPM0G3507App.elf.dir/build.make CMakeFiles/MSPM0G3507App.elf.dir/src/common/gpio_toggle_output.c.i
.PHONY : src/common/gpio_toggle_output.c.i

src/common/gpio_toggle_output.s: src/common/gpio_toggle_output.c.s
.PHONY : src/common/gpio_toggle_output.s

# target to generate assembly for a file
src/common/gpio_toggle_output.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MSPM0G3507App.elf.dir/build.make CMakeFiles/MSPM0G3507App.elf.dir/src/common/gpio_toggle_output.c.s
.PHONY : src/common/gpio_toggle_output.c.s

src/common/startup_mspm0g350x_gcc.o: src/common/startup_mspm0g350x_gcc.c.o
.PHONY : src/common/startup_mspm0g350x_gcc.o

# target to build an object file
src/common/startup_mspm0g350x_gcc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MSPM0G3507App.elf.dir/build.make CMakeFiles/MSPM0G3507App.elf.dir/src/common/startup_mspm0g350x_gcc.c.o
.PHONY : src/common/startup_mspm0g350x_gcc.c.o

src/common/startup_mspm0g350x_gcc.i: src/common/startup_mspm0g350x_gcc.c.i
.PHONY : src/common/startup_mspm0g350x_gcc.i

# target to preprocess a source file
src/common/startup_mspm0g350x_gcc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MSPM0G3507App.elf.dir/build.make CMakeFiles/MSPM0G3507App.elf.dir/src/common/startup_mspm0g350x_gcc.c.i
.PHONY : src/common/startup_mspm0g350x_gcc.c.i

src/common/startup_mspm0g350x_gcc.s: src/common/startup_mspm0g350x_gcc.c.s
.PHONY : src/common/startup_mspm0g350x_gcc.s

# target to generate assembly for a file
src/common/startup_mspm0g350x_gcc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MSPM0G3507App.elf.dir/build.make CMakeFiles/MSPM0G3507App.elf.dir/src/common/startup_mspm0g350x_gcc.c.s
.PHONY : src/common/startup_mspm0g350x_gcc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MSPM0G3507App.elf"
	@echo "... generated/G3507/ti_msp_dl_config.o"
	@echo "... generated/G3507/ti_msp_dl_config.i"
	@echo "... generated/G3507/ti_msp_dl_config.s"
	@echo "... src/common/gpio_toggle_output.o"
	@echo "... src/common/gpio_toggle_output.i"
	@echo "... src/common/gpio_toggle_output.s"
	@echo "... src/common/startup_mspm0g350x_gcc.o"
	@echo "... src/common/startup_mspm0g350x_gcc.i"
	@echo "... src/common/startup_mspm0g350x_gcc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

